spring.application.name=microservicios-auth
server.port=8095

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${random.value}

# Misma BD PostgreSQL que ms-usuarios
spring.datasource.url=jdbc:postgresql://localhost:5432/db_microservicios_usuarios
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# JWT — usar variable de entorno en produccion: ${JWT_SECRET}
app.jwt.secret=M1cr0s3rv1c10s-JWT-S3cr3t-K3y-Sup3r-S3gur4-2024!
# 1 hora en milisegundos
app.jwt.expiration-ms=3600000

logging.level.org.hibernate.SQL=debug

# Actuator — observabilidad
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true
