spring.application.name=microservicios-eureka-server
server.port=8761

#no registrase asi mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


# Actuator — observabilidad
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true
